### ISSUE TITLE
[Question]: How to get RedisInsight to work with PersistentVolumeClaim on Microk8s?

### ISSUE THREAD

**Issue by m4rc3l-h3** [RedisInsight/RedisInsight#1315]
**Preconditions** (Any important steps we need to know)
- On the nfs server is created and exported a directory (mod 777 and 1001:1001 ownership)
- I installed RedisInsight following https://docs.redis.com/latest/ri/installing/install-k8s/ on microk8s using the below yaml files in the following order: pv, pvc, deployment, service

deployment.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-insight
  name: redis-insight
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - image: redislabs/redisinsight:latest
        name: redis-insight
        env:
          - name: RIHOST
           value: 0.0.0.0
          - name: RIPORT
            value:  "8001"
          - name: RIHOMEDIR
            value: /db
          - name: RILOGDIR
            value: /db
        volumeMounts:
          - name: db 
            mountPath: /db
        ports:
        - containerPort: 8001
          name: redis-ui-port
      volumes:
        - name: db
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: pvc-nfs-redis-insight
```

service.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: redis-insight
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: redis-ui-port
```

persistent-volume-claim.yaml
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-redis-insight
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

persistent-volume.yaml
``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-redis-insight
  labels:
    type: nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/redis-insight/
    server: nfs.local
    readOnly: false
```

data dir on nfs-server (exported as srv/redis-insight) after container start:
``` yaml
/mnt/redis-insight$ ls -aln
total 24
drwxrwxrwx 6 1001 1001 4096 Okt 22 15:17 .
drwxr-xr-x 6 1000 1000 4096 Okt 22 15:16 ..
drwxr-xr-x 2 1001 1001 4096 Okt 22 15:17 bulk_operation
drwxr-xr-x 2 1001 1001 4096 Okt 22 15:17 dropbox
drwxr-xr-x 2 1001 1001 4096 Okt 22 15:17 profiler_logs
-rw-r--r-- 1 1001 1001    0 Okt 22 15:17 queries.log
-rw-r--r-- 1 1001 1001    0 Okt 22 15:17 redisinsight.db
-rw-r--r-- 1 1001 1001    0 Okt 22 15:17 redisinsight.log
drwxr-xr-x 2 1001 1001 4096 Okt 22 15:17 rsnaps
```

**Steps to reproduce** (How to reproduce what you found step by step)
In deployment.yaml change from emptyDir to persistentVolumeClaim.

**Actual behavior** (A short description of what you found)
After executing above change in deployment.yaml, InsightRedis 
- data is written to the nfs share (see above)
- not accessible anymore via Service (in contrast to emptyDir in deployment.yaml)
- after some time an exception is written to /db/redisinsight.log (see under additional context)

**Expected behavior** (A short description of what you expected to find)
InsightRedis is accessible with persistenVolumeClaim, i.e., similar to using emptyDir.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
n. a.

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
- microk8s version: MicroK8s v1.25.2 revision 4055
- microk8s addons:
    dns
    ha-cluster
    helm
    helm3
    metallb
    registry
- RedisInsight Image: latest
- No events recorded in `kubectl describe pod/...`
- `/db/redisinsight.log`:
``` bash
ERROR 2022-10-22 14:34:14,496 redisinsight_startup Error in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 475, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./startup.py", line 565, in main
  File "./startup.py", line 384, in main_console
  File "./startup.py", line 136, in run_web_app
  File "./startup.py", line 104, in run_migrations
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 108, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 58, in has_table
    tables = self.connection.introspection.table_names(cursor)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/introspection.py", line 58, in table_names
    return get_names(cursor)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    for ti in self.get_table_list(cursor)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/introspection.py", line 80, in get_table_list
    cursor.execute(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 475, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: database is locked
```

Any help is much appreciated. Thank you in advance!

**Comment by GnaneshKunal** [comment]
@m4rc3l-h3 

Can you once check if the NFS is mounted in read-only mode?

**Comment by m4rc3l-h3** [comment]
@GnaneshKunal : Thanks for your reply. Below you find the info from the nfs server. I also connected to the container using `kubectl exec -it  pods/... -- /bin/bash` and executed `touch test` in the mounted folder. The file is successfully created in the folder and on the nfs server. 
Please let me know if you need anything else. Thank you in advance!

Extract from `/etc/exports`:
``` bash
/srv/redis-insight              xx.xx.xx.xx/(rw,sync,root_squash,no_subtree_check)
```

**Comment by m4rc3l-h3** [comment]
As described [here](https://discuss.kubernetes.io/t/write-permissions-on-volume-mount-with-security-context-fsgroup-option/16524/4) it is not a RedisInsight issue. Rather my issue emerged from NFS `PersistentVolume` not supporting `SecurityContext`.
I could resolve my issue using [csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs).
