### ISSUE TITLE
[Bug]: IPV6-only DNS record are not resolved, but connection by IP works fine

### ISSUE THREAD

**Issue by michail-nikolaev** [RedisInsight/RedisInsight#1429]
**Preconditions** (Any important steps we need to know)
Redis cluster with ipv6-only connection.

**Steps to reproduce** (How to reproduce what you found step by step)
Attempt to connect to it using DNS.

**Actual behavior** (A short description of what you found)
Error is shown.

**Expected behavior** (A short description of what you expected to find)
App is connected to the cluster.

**Workaround**:
Enter IPV6 address instead of DNS.

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 10. 
Version 2.12.0

**Comment by michail-nikolaev** [comment]
I see connection timeout.

It works with CLI. 

And works with direct IPv6 in Host field.

One moment here - DNS is CNAME to other record.

**Comment by CanRau** [comment]
If you're by any chance using fly.io and trying to connect to a [6pn address](https://fly.io/docs/reference/private-networking/) `fly proxy` worked for me as shown [here](https://community.fly.io/t/using-wireguard-to-display-a-table-like-structure-for-stored-prisma-sqlite-db/6262/4?u=canrau)

**Comment by BlakeB415** [comment]
I’m also experiencing this. Using the direct IPv6 literal works, but not the DNS.

**Comment by darwin67** [comment]
Well, turns out this is still a problem.

We also have DNS that resolves to IPv6 addresses, and I thought I was crazy when it keeps returning me an error failing to connect. Even though I gave all the right params.

We also have a self-signed CA bundle passed in, but we've confirmed that CLI connects fine, and our main application also connects correctly. Just seems like RedisInsight itself is incapable.

Here are the logs when I turned logging to debug level if it helps..
```
[Redis Insight] 1 2/28/2025, 1:08:33 AM   ERROR [IoredisRedisConnectionStrategy] Failed connection to the redis oss cluster - {
  stack: '[ {} ]',
  error: {
    message: 'Failed to refresh slots cache.',
    stack: 'ClusterAllFailedError: Failed to refresh slots cache.\n' +
      '    at tryNode (/usr/src/app/redisinsight/api/node_modules/ioredis/built/cluster/index.js:308:31)\n' +
      '    at /usr/src/app/redisinsight/api/node_modules/ioredis/built/cluster/index.js:325:21\n' +
      '    at Timeout.<anonymous> (/usr/src/app/redisinsight/api/node_modules/ioredis/built/cluster/index.js:662:24)\n' +
      '    at Timeout.run (/usr/src/app/redisinsight/api/node_modules/ioredis/built/utils/index.js:117:22)\n' +
      '    at listOnTimeout (node:internal/timers:575:11)\n' +
      '    at process.processTimers (node:internal/timers:514:7)'
  },
  data: [
    {
      sessionMetadata: {
        userId: '1',
        sessionId: '1',
        correlationId: '53c48edd-8956-45d1-833d-d9e53646e608'
      },
      databaseId: '0882ce67-2abf-433f-a99f-20592289786e',
      context: 'Common'
    }
  ]
}
[Redis Insight] 1 2/28/2025, 1:08:33 AM    WARN [IoredisRedisConnectionStrategy] Server closed the connection. - {
  data: [
    {
      sessionMetadata: {
        userId: '1',
        sessionId: '1',
        correlationId: '53c48edd-8956-45d1-833d-d9e53646e608'
      },
      databaseId: '0882ce67-2abf-433f-a99f-20592289786e',
      context: 'Common'
    }
  ],
  stack: '[]'
}
```

**Comment by Sylvain-Royer** [comment]
I've run into this issue as well. This seems to be an issue with the cluster info parser not handling ipv6 ips properly.

I've submitted a PR [here](https://github.com/RedisInsight/RedisInsight/pull/4632) with the fix. I've tested this locally via docker-compose as well as within my company's ipv6 only k8s cluster.
