### ISSUE TITLE
Cluster detected but lot of timed out (running in k8s)

### ISSUE THREAD

**Issue by goldyfruit** [RedisInsight/RedisInsight#1821]
I'm running a Redis Cluster within Kubernetes which is working fine _(not deployed by any operator, just a `StateFullSet` application, a PVC and a headless service)_.

I install RedisInsight 1.13.1 by following [this documentation](https://docs.redis.com/latest/ri/installing/install-k8s/), the install went well, the cluster detection as well _(using the DNS from the headless service)_.

![image](https://user-images.githubusercontent.com/614115/223807128-f1faba3c-8688-4fdb-a981-181a380f717f.png)

![image](https://user-images.githubusercontent.com/614115/223807070-1bd93c27-c9d1-41ae-82f5-30e309d8d1e7.png)

But when I try to browse or insert a key it hangs and from the RedisInsight logs I got these traces _(both Redis Cluster and Redis Insight are in the same namespace)_.

![image](https://user-images.githubusercontent.com/614115/223807318-1dcb1358-83e8-4b9f-88b7-24ca76ac38c7.png)

```
INFO 2023-03-08 17:08:04,855 redisinsight_startup Starting waitress
INFO:redisinsight_startup:Starting waitress
INFO:backoff:Backing off send_request(...) for 0.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c353110>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 1.9s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c3724d0>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c371ed0>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 0.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c371350>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 12.2s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c34a790>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c348c10>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 35.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c363b90>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 45.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c363c90>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 248.6s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c3628d0>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 198.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c123e90>: Failed to establish a new connection: [Errno 111] Connection refused')))
ERROR:backoff:Giving up send_request(...) after 11 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c334950>: Failed to establish a new connection: [Errno 111] Connection refused')))

INFO 2023-03-08 17:59:06,008 redisinsight Initialized index.html cache
INFO:redisinsight:Initialized index.html cache
INFO:backoff:Backing off send_request(...) for 0.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c349450>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c389e50>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 3.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c0c7750>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 0.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c337850>: Failed to establish a new connection: [Errno 111] Connection refused')))
INFO:backoff:Backing off send_request(...) for 4.9s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba3c248910>: Failed to establish a new connection: [Errno 111] Connection refused')))
ERROR 2023-03-08 17:59:47,108 redisinsight Something went wrong - caught generic exception
Traceback (most recent call last):
  File "./redisinsight/cluster_management/decorators.py", line 18, in wrapped_view
  File "./redisinsight/cluster_management/decorators.py", line 59, in _wrapped_view
  File "./redisinsight/cluster_management/views.py", line 180, in create_migration_plan
KeyError: '10.233.98.173:6379'
ERROR:redisinsight:Something went wrong - caught generic exception
Traceback (most recent call last):
  File "./redisinsight/cluster_management/decorators.py", line 18, in wrapped_view
  File "./redisinsight/cluster_management/decorators.py", line 59, in _wrapped_view
  File "./redisinsight/cluster_management/views.py", line 180, in create_migration_plan
KeyError: '10.233.98.173:6379'
INFO:backoff:Backing off send_request(...) for 15.2s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba383ae150>: Failed to establish a new connection: [Errno 111] Connection refused')))
ERROR 2023-03-08 17:59:51,443 redisinsight Something went wrong - caught generic exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/cluster_management/decorators.py", line 18, in wrapped_view
  File "./redisinsight/cluster_management/decorators.py", line 59, in _wrapped_view
  File "./redisinsight/cluster_management/views.py", line 284, in cluster_alerts
  File "./redisinsight/cluster_management/services/api.py", line 181, in get_actual_migration_plan
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
ERROR:redisinsight:Something went wrong - caught generic exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/cluster_management/decorators.py", line 18, in wrapped_view
  File "./redisinsight/cluster_management/decorators.py", line 59, in _wrapped_view
  File "./redisinsight/cluster_management/views.py", line 284, in cluster_alerts
  File "./redisinsight/cluster_management/services/api.py", line 181, in get_actual_migration_plan
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
```

Thanks for your help.

**Comment by goldyfruit** [comment]
Same when I try to download an RBD file.

![image](https://user-images.githubusercontent.com/614115/223808599-f1bbb572-848e-4faf-8dff-81d76b8424cc.png)

```
INFO 2023-03-08 18:55:05,476 redisinsight Downloading RDB File...
INFO:redisinsight:Downloading RDB File...
ERROR 2023-03-08 18:55:20,502 redisinsight Error during memory analysis (snapshot ID: 39b16f6f-9390-4b3d-ae02-18fc3d93fce1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 273, in analyze_instance
  File "./redisinsight/memory_analysis/services/analysis/dump.py", line 63, in download_rdb_using_sync
  File "./redisinsight/core/services/redis_conn.py", line 497, in send_command
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 698, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
ERROR:redisinsight:Error during memory analysis (snapshot ID: 39b16f6f-9390-4b3d-ae02-18fc3d93fce1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 273, in analyze_instance
  File "./redisinsight/memory_analysis/services/analysis/dump.py", line 63, in download_rdb_using_sync
  File "./redisinsight/core/services/redis_conn.py", line 497, in send_command
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 698, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
ERROR 2023-03-08 18:55:20,522 redisinsight Error in memory analysis job
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 273, in analyze_instance
  File "./redisinsight/memory_analysis/services/analysis/dump.py", line 63, in download_rdb_using_sync
  File "./redisinsight/core/services/redis_conn.py", line 497, in send_command
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 698, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 367, in run_memory_analysis_job
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 339, in analyze_instance
Exception: Error during instance analysis
ERROR:redisinsight:Error in memory analysis job
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 273, in analyze_instance
  File "./redisinsight/memory_analysis/services/analysis/dump.py", line 63, in download_rdb_using_sync
  File "./redisinsight/core/services/redis_conn.py", line 497, in send_command
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 698, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 367, in run_memory_analysis_job
  File "./redisinsight/memory_analysis/services/analysis/__init__.py", line 339, in analyze_instance
Exception: Error during instance analysis
DEBUG 2023-03-08 18:55:20,543 redisinsight Future <Future at 0x7fba3bcae7d0 state=finished raised Exception> finished
DEBUG:redisinsight:Future <Future at 0x7fba3bcae7d0 state=finished raised Exception> finished
```

**Comment by goldyfruit** [comment]
![image](https://user-images.githubusercontent.com/614115/223846543-a6fa4c08-aa33-4981-9c88-2184126bf7db.png)

**Comment by goldyfruit** [comment]
I flushed my Redis Cluster _(and it's volumes and service)_, create a fresh cluster and now it's working fine.

Don't know if it's related to CoreDNS or something else, I'm gonna close this issue _(sorry for the noise)_.

**Comment by xyfleet** [comment]
@goldyfruit Hi 
I met an issue when I tried to add AWS ElastiCache into Redisinsight.
After installing the RedisInsight into EKS cluster, I cannot add my ElastiCache cluster into the RedisInsight. 
More, there is no log from the redisinsight pod. 
The endpoint of my redis cluster:
clustercfg.xxxx-primary-cluster.yyyyyy.cache.amazonaws.com


![Screenshot2024_04_11_144423](https://github.com/RedisInsight/RedisInsight/assets/113627389/3d4462d8-df11-4554-9fef-5e6f4957f5c8)

How do you add your ElastiCache into the RedisInsight? Thanks.
