### ISSUE TITLE
[Bug]: Failed to build docker image according to wiki

### ISSUE THREAD

**Issue by moluzhui** [RedisInsight/RedisInsight#416]
**Steps to reproduce** (How to reproduce what you found step by step)
1. Download `RedisInsight-2.0.4-preview.tar.gz` for github release
2. Unzip and run `docker build -t redisinsight .` according to the [wiki](https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute#build-docker-image-with-ui)
Then 

https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute#build-docker-image-with-ui

**Actual behavior** (A short description of what you found)
Then in the middle stage of the build I get the following error:
```
....
Step 13/43 : FROM node:14.17-alpine as back
 ---> 1d909dafa77f
Step 14/43 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7ee25757a69c
Step 15/43 : COPY redisinsight/api/package.json redisinsight/api/yarn.lock ./
 ---> Using cache
 ---> 230a417c9bf3
Step 16/43 : yarn install
 ---> Running in f5e1d418df0d
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/core@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > ioredis-mock@5.8.1" has unmet peer dependency "redis-commands@1.x".
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /usr/src/app/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || npm run build
Arguments:
Directory: /usr/src/app/node_modules/keytar
Output:
prebuild-install WARN install Request timed out
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1647850378402-0.5127244545494067/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.7.0 build /usr/src/app/node_modules/keytar
> node-gyp rebuild

gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:397:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:409:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Linux 3.10.0-1062.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/keytar
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.7.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-21T08_13_29_632Z-debug.log
The command '/bin/sh -c yarn config set registry https://registry.npm.taobao.org && yarn install' returned a non-zero code: 1
```

**Expected behavior** (A short description of what you expected to find)
Image Building succeeded

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
- OS: Centos7
- redisinsight: v2.0.4-preview
- Docker version: 
```
docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by moluzhui** [comment]
Sorry, this seems to be a network problem, and it will work again when it is rebuilt today
