### ISSUE TITLE
[Bug]: The project of v2.0.5 tag building image has no such file or directory error

### ISSUE THREAD

**Issue by moluzhui** [RedisInsight/RedisInsight#467]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
1. download project by `git clone --depth 1 --branch 2.0.5 https://github.com/RedisInsight/RedisInsight.git`
2. build image by `docker build -t redisinsight:2.0.5 .`

**Actual behavior** (A short description of what you found)
When the following steps are executed, an error will be reported
```
COPY --from=front /usr/src/app/redisinsight/api/defaults ./defaults
COPY failed: stat /data/docker/overlay2/2b1c26f136a8ac19b7915b3fe6383d5230541c36a36a5516d50ac275b2807472/merged/usr/src/app/redisinsight/api/defaults: no such file or directory
```

**Expected behavior** (A short description of what you expected to find)
Build docker image successfully

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
- OS: centos7
- docker version
```
 docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Looking forward to your feedback, thank you.

**Comment by ViktarStarastsenka** [comment]
Hi @moluzhui , could you try to run docker build with --no-cache flag?
If it does not help, please send your logs from the docker build command.

**Comment by moluzhui** [comment]
Hi @ViktarStarastsenka, sorry I can't collect the complete process of building based on `--no-cache`, this is because of network problems(**see first point**, I add **alibaba source** in dockerfile), it has already reported an error in `[4/4] Building fresh packages...`(**see second point**), then I closed no-cache, and then several times after build, go to the last `no such file or directory`.(**see third point**)
1. Dockerfile
```Dockerfile
FROM node:14.17-alpine as front
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++
WORKDIR /usr/src/app
COPY package.json yarn.lock babel.config.js tsconfig.json ./
COPY configs ./configs
COPY scripts ./scripts
COPY redisinsight ./redisinsight
RUN yarn config set registry https://registry.npm.taobao.org/ && \
    yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/ && \
    yarn config set ELECTRON_BUILDER_BINARIES_MIRROR http://npm.taobao.org/mirrors/electron-builder-binaries/ && \
    SKIP_POSTINSTALL=1 yarn install
RUN yarn --cwd redisinsight/api
RUN yarn build:web
RUN yarn build:statics

FROM node:14.17-alpine as back
WORKDIR /usr/src/app
COPY redisinsight/api/package.json redisinsight/api/yarn.lock ./
RUN yarn config set registry https://registry.npm.taobao.org/ && \
    yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/ && \
    yarn config set ELECTRON_BUILDER_BINARIES_MIRROR http://npm.taobao.org/mirrors/electron-builder-binaries/ && \
    yarn install
COPY redisinsight/api ./
COPY --from=front /usr/src/app/redisinsight/api/static ./static
COPY --from=front /usr/src/app/redisinsight/api/defaults ./defaults
RUN yarn run build:prod

FROM node:14.17-slim
# Set up mDNS functionality, to play well with Redis Enterprise
# clusters on the network.
RUN set -ex \
 && DEPS="avahi-daemon libnss-mdns" \
 && apt-get update && apt-get install -y --no-install-recommends $DEPS \
 # Disable nss-mdns's two-label limit heuristic so that host names
 # with multiple labels can be resolved.
 # E.g. redis-12000.rediscluster.local, which has 3 labels.
 # (https://github.com/lathiat/nss-mdns#etcmdnsallow)
 && echo '*' > /etc/mdns.allow \
 # Configure NSSwitch to use the mdns4 plugin so mdns.allow is respected
 && sed -i "s/hosts:.*/hosts:          files mdns4 dns/g" /etc/nsswitch.conf \
 # We run a `avahi-daemon` without `dbus` so that we can start it as a
 # non-root user. `dbus` requires root permissions to start. And
 # anyway, there's a way to run `avahi-daemon` without `dbus` so why
 # shouldn't we use it.  https://linux.die.net/man/5/avahi-daemon.conf
 && printf "[server]\nenable-dbus=no\n" >> /etc/avahi/avahi-daemon.conf \
 && chmod 777 /etc/avahi/avahi-daemon.conf \
 # We create the directory because when the first time `avahi-daemon`
 # is run, the directory doesn't exist and the `avahi-daemon` must have
 # permissions to create the directory under `/var`.
 && mkdir -p /var/run/avahi-daemon \
 # Change the permissions of the directories avahi will use.
 && chown avahi:avahi /var/run/avahi-daemon \
 && chmod 777 /var/run/avahi-daemon

RUN apt-get install net-tools
RUN apt-get install -y dbus-x11 gnome-keyring libsecret-1-0
RUN dbus-uuidgen > /var/lib/dbus/machine-id

ARG NODE_ENV=production
ARG SERVER_TLS_CERT
ARG SERVER_TLS_KEY
ENV SERVER_TLS_CERT=${SERVER_TLS_CERT}
ENV SERVER_TLS_KEY=${SERVER_TLS_KEY}
ENV NODE_ENV=${NODE_ENV}
ENV SERVER_STATIC_CONTENT=true
ENV BUILD_TYPE='DOCKER_ON_PREMISE'
WORKDIR /usr/src/app
COPY --from=back /usr/src/app/dist ./redisinsight/api/dist
COPY --from=front /usr/src/app/redisinsight/ui/dist ./redisinsight/ui/dist

# Build BE prod dependencies here to build native modules
COPY redisinsight/api/package.json redisinsight/api/yarn.lock ./redisinsight/api/
RUN yarn --cwd ./redisinsight/api install --production
COPY redisinsight/api/.yarnclean.prod ./redisinsight/api/.yarnclean
RUN yarn --cwd ./redisinsight/api autoclean --force

COPY ./docker-entry.sh ./
RUN chmod +x docker-entry.sh

EXPOSE 5000

ENTRYPOINT ["./docker-entry.sh", "node", "redisinsight/api/dist/src/main"]
```

2. use --no-cache
```
docker build -t redisinsight:2.0.5 . --no-cache
Sending build context to Docker daemon  11.83MB
Step 1/44 : FROM node:14.17-alpine as front
 ---> 1d909dafa77f
Step 2/44 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update
 ---> Running in db8a36b90efc
fetch http://mirrors.aliyun.com/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.13-8-gaf7d80ff31 [http://mirrors.aliyun.com/alpine/v3.11/main]
v3.11.11-124-gf2729ece5a [http://mirrors.aliyun.com/alpine/v3.11/community]
OK: 11277 distinct packages available
Removing intermediate container db8a36b90efc
 ---> f3513d5622cf
Step 3/44 : RUN apk add --no-cache --virtual .gyp         python         make         g++
 ---> Running in 2ed8739359a8
fetch http://mirrors.aliyun.com/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/22) Installing libbz2 (1.0.8-r1)
(2/22) Installing expat (2.2.9-r1)
(3/22) Installing libffi (3.2.1-r6)
(4/22) Installing gdbm (1.13-r1)
(5/22) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(6/22) Installing ncurses-libs (6.1_p20200118-r4)
(7/22) Installing readline (8.0.1-r0)
(8/22) Installing sqlite-libs (3.30.1-r2)
(9/22) Installing python2 (2.7.18-r0)
(10/22) Installing make (4.2.1-r2)
(11/22) Installing binutils (2.33.1-r1)
(12/22) Installing gmp (6.1.2-r1)
(13/22) Installing isl (0.18-r0)
(14/22) Installing libgomp (9.3.0-r0)
(15/22) Installing libatomic (9.3.0-r0)
(16/22) Installing mpfr4 (4.0.2-r1)
(17/22) Installing mpc1 (1.1.0-r1)
(18/22) Installing gcc (9.3.0-r0)
(19/22) Installing musl-dev (1.1.24-r3)
(20/22) Installing libc-dev (0.7.2-r0)
(21/22) Installing g++ (9.3.0-r0)
(22/22) Installing .gyp (20220402.071158)
Executing busybox-1.31.1-r10.trigger
OK: 212 MiB in 38 packages
Removing intermediate container 2ed8739359a8
 ---> 03eac312a465
Step 4/44 : WORKDIR /usr/src/app
 ---> Running in 18e9c94546bc
Removing intermediate container 18e9c94546bc
 ---> 364fa176f317
Step 5/44 : COPY package.json yarn.lock babel.config.js tsconfig.json ./
 ---> 2a862beab673
Step 6/44 : COPY configs ./configs
 ---> d2c0c74f63d1
Step 7/44 : COPY scripts ./scripts
 ---> 92a64cba69d6
Step 8/44 : COPY redisinsight ./redisinsight
 ---> 8eb1090ec3a0
Step 9/44 : RUN yarn config set registry https://registry.npm.taobao.org/ &&     yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/ &&     yarn config set ELECTRON_BUILDER_BINARIES_MIRROR http://npm.taobao.org/mirrors/electron-builder-binaries/ &&     SKIP_POSTINSTALL=1 yarn install
 ---> Running in 5b54ffb4a7dc
yarn config v1.22.5
success Set "registry" to "https://registry.npm.taobao.org/".
Done in 0.10s.
yarn config v1.22.5
success Set "ELECTRON_MIRROR" to "http://npm.taobao.org/mirrors/electron/".
Done in 0.12s.
yarn config v1.22.5
success Set "ELECTRON_BUILDER_BINARIES_MIRROR" to "http://npm.taobao.org/mirrors/electron-builder-binaries/".
Done in 0.12s.
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.9: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.6: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @elastic/datemath@5.0.3" has unmet peer dependency "moment@^2.24.0".
warning " > @elastic/eui@34.6.0" has unmet peer dependency "@types/react@^16.9.34".
warning " > @elastic/eui@34.6.0" has incorrect peer dependency "@types/react-dom@^16.9.6".
warning " > @elastic/eui@34.6.0" has unmet peer dependency "moment@^2.13.0".
warning " > @elastic/eui@34.6.0" has unmet peer dependency "prop-types@^15.5.0".
warning " > @elastic/eui@34.6.0" has incorrect peer dependency "react@^16.12".
warning " > @elastic/eui@34.6.0" has incorrect peer dependency "react-dom@^16.12".
warning "@elastic/eui > react-ace@7.0.5" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
warning "@elastic/eui > react-ace@7.0.5" has incorrect peer dependency "react-dom@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
warning "@elastic/eui > react-input-autosize@2.2.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning " > react-monaco-editor@0.44.0" has unmet peer dependency "@types/react@^17.x".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > @nestjs/testing@7.6.5" has unmet peer dependency "@nestjs/common@^7.0.0".
warning " > @nestjs/testing@7.6.5" has unmet peer dependency "@nestjs/core@^7.0.0".
warning " > cache-loader@4.1.0" has incorrect peer dependency "webpack@^4.0.0".
warning " > ioredis-mock@5.5.4" has unmet peer dependency "ioredis@4.x".
warning " > ioredis-mock@5.5.4" has unmet peer dependency "redis-commands@1.x".
warning " > monaco-editor-webpack-plugin@6.0.0" has unmet peer dependency "monaco-editor@0.30.x".
warning " > ts-jest@26.1.0" has incorrect peer dependency "typescript@>=3.8 <4.0".
[4/4] Building fresh packages...
$ skip-postinstall || (electron-builder install-app-deps && yarn webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock)
Done in 178.98s.
Removing intermediate container 5b54ffb4a7dc
 ---> 2e7dc5d8c9d2
Step 10/44 : RUN yarn --cwd redisinsight/api
 ---> Running in a7e225fbeec7
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/core@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > ioredis-mock@5.8.1" has unmet peer dependency "redis-commands@1.x".
[4/4] Building fresh packages...
error /usr/src/app/redisinsight/api/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || npm run build
Arguments: 
Directory: /usr/src/app/redisinsight/api/node_modules/keytar
Output:
prebuild-install WARN install connect ETIMEDOUT 185.199.111.133:443
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1648883937011-0.05091857960781154/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.7.0 build /usr/src/app/redisinsight/api/node_modules/keytar
> node-gyp rebuild

/bin/sh: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1062.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/redisinsight/api/node_modules/keytar
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.7.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-02T07_21_06_336Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --cwd redisinsight/api' returned a non-zero code: 1
```

3. not use --no-cache, 
```
docker build -t redisinsight:2.0.5 .
Sending build context to Docker daemon  11.83MB
Step 1/44 : FROM node:14.17-alpine as front
 ---> 1d909dafa77f
Step 2/44 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update
 ---> Using cache
 ---> 6195ac45423e
Step 3/44 : RUN apk add --no-cache --virtual .gyp         python         make         g++
 ---> Using cache
 ---> e253e0091703
Step 4/44 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 79e4d904a8d6
Step 5/44 : COPY package.json yarn.lock babel.config.js tsconfig.json ./
 ---> Using cache
 ---> eaa60a4f7353
Step 6/44 : COPY configs ./configs
 ---> Using cache
 ---> fb09e33bc128
Step 7/44 : COPY scripts ./scripts
 ---> Using cache
 ---> c1fe46b52a84
Step 8/44 : COPY redisinsight ./redisinsight
 ---> Using cache
 ---> 950fd0bc967e
Step 9/44 : RUN yarn config set registry https://registry.npm.taobao.org/ &&     yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/ &&     yarn config set ELECTRON_BUILDER_BINARIES_MIRROR http://npm.taobao.org/mirrors/electron-builder-binaries/ &&     SKIP_POSTINSTALL=1 yarn install
 ---> Using cache
 ---> c8f0d5e9206f
Step 10/44 : RUN yarn --cwd redisinsight/api
 ---> Using cache
 ---> 733f2d6f9b26
Step 11/44 : RUN yarn build:web
 ---> Using cache
 ---> eba88498b84f
Step 12/44 : RUN yarn build:statics
 ---> Using cache
 ---> 93e5e83d9ab9
Step 13/44 : FROM node:14.17-alpine as back
 ---> 1d909dafa77f
Step 14/44 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7ee25757a69c
Step 15/44 : COPY redisinsight/api/package.json redisinsight/api/yarn.lock ./
 ---> Using cache
 ---> 12fc1880ecfd
Step 16/44 : RUN yarn config set registry https://registry.npm.taobao.org/ &&     yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/ &&     yarn config set ELECTRON_BUILDER_BINARIES_MIRROR http://npm.taobao.org/mirrors/electron-builder-binaries/ &&     yarn install
 ---> Using cache
 ---> 99194b4fcda5
Step 17/44 : COPY redisinsight/api ./
 ---> Using cache
 ---> afbeb043014e
Step 18/44 : COPY --from=front /usr/src/app/redisinsight/api/static ./static
 ---> Using cache
 ---> 078a3b069886
Step 19/44 : COPY --from=front /usr/src/app/redisinsight/api/defaults ./defaults
COPY failed: stat /data/docker/overlay2/531c511ed608d19ad8818f9d55048663660a8325b94a8ef487efd2623603e442/merged/usr/src/app/redisinsight/api/defaults: no such file or directory
```

**Comment by arthosofteq** [comment]
Hi, @moluzhui! 
As I can see for some reason prebuild was not able to download binary for the keytar module `prebuild-install WARN install connect ETIMEDOUT 185.199.111.133:443`. After that gyp tried to create it but there is no required dependencies `gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp`
So you have 2 options here:
 - somehow resolve ETIMEDOUT issue then prebuild will download keytar binary
 - install required dependencies to build keytar.node binary (`libsecret` is required. You could add `apk add libsecret` for intermediate images before `yarn install` commands)

**Comment by moluzhui** [comment]
Hi, @arthosofteq  I used your second method, the command is as follows, but it still returns an error
```
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        libsecret
```
Error is as follows
```
Step 11/50 : RUN SKIP_POSTINSTALL=1 yarn install
 ---> Using cache
 ---> 48639b318142
Step 12/50 : RUN yarn --cwd redisinsight/api
 ---> Running in 4687d52e1d07
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/platform-socket.io@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/common@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "@nestjs/core@^8.0.0".
warning " > @nestjs/websockets@8.2.4" has incorrect peer dependency "rxjs@^7.1.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > ioredis-mock@5.8.1" has unmet peer dependency "redis-commands@1.x".
[4/4] Building fresh packages...
error /usr/src/app/redisinsight/api/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || npm run build
Arguments: 
Directory: /usr/src/app/redisinsight/api/node_modules/keytar
Output:
prebuild-install WARN install connect ETIMEDOUT 185.199.109.133:443
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1650440673366-0.29677887218741517/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.7.0 build /usr/src/app/redisinsight/api/node_modules/keytar
> node-gyp rebuild

/bin/sh: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1062.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/redisinsight/api/node_modules/keytar
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.7.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-20T07_46_42_399Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --cwd redisinsight/api' returned a non-zero code: 1
```

**Comment by moluzhui** [comment]
@arthosofteq  This seems to be a network problem, and in one build it passed, but the default directory was not found, as was the original error
```
Step 23/50 : COPY redisinsight/api ./
 ---> Using cache
 ---> b714e21dca91
Step 24/50 : COPY --from=front /usr/src/app/redisinsight/api/static ./static
 ---> Using cache
 ---> 4115797662c0
Step 25/50 : COPY --from=front /usr/src/app/redisinsight/api/defaults ./defaults
COPY failed: stat /data/docker/overlay2/a2746c187f291634e4fe82949adec981ec80bda359cc80bed9cb4faa6be12fbd/merged/usr/src/app/redisinsight/api/defaults: no such file or directory
```
