### ISSUE TITLE
Development on M1 based Macs (Apple Silicon, arm64)

### ISSUE THREAD

**Issue by joeyguerra** [RedisInsight/RedisInsight#481]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
node-sass does not support the M1 architecture.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every time someone with an M1 based Mac tries to build the app for development.

**Alternatives considered** (Describe any alternative features or products you've considered).
sass or css variables

**Additional information** (Add any other context or details here).
End of the console output when running

```bash
yarn package
```

```bash
ERROR in ./redisinsight/ui/src/pages/workbench/components/wb-view/WBView/styles.module.scss
[1] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[1] ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
[1] Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
[1] For more information on which environments are supported please see:
[1] https://github.com/sass/node-sass/releases/tag/v5.0.0
[1]     at Object.emitError (/Users/<redacted>/src/<redacted>/RedisInsight/node_modules/webpack/lib/NormalModule.js:447:6)
[1]     at getSassImplementation (/Users/<redacted>/src/<redacted>/RedisInsight/node_modules/sass-loader/dist/utils.js:59:21)
[1]     at Object.loader (/Users/<redacted>/src/<redacted>/RedisInsight/node_modules/sass-loader/dist/index.js:35:59)
[1]  @ ./redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx 27:0-42 75:35-51 90:15-26 98:18-32 98:54-70 118:18-32 118:54-70 145:17-34 170:17-36 184:20-39 184:41-65
[1]  @ ./redisinsight/ui/src/pages/workbench/components/wb-view/WBView/index.ts 10:0-30 11:15-21
[1]  @ ./redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx 28:0-30 207:42-48
[1]  @ ./redisinsight/ui/src/pages/workbench/components/wb-view/index.ts 10:0-44 11:15-28
[1]  @ ./redisinsight/ui/src/pages/workbench/WorkbenchPage.tsx 25:0-49 67:42-55
[1]  @ ./redisinsight/ui/src/pages/workbench/index.ts 10:0-44 11:15-28
[1]  @ ./redisinsight/ui/src/components/main-router/constants/defaultRoutes.ts 14:0-50 23:13-26
[1]  @ ./redisinsight/ui/src/components/main-router/MainRouter.tsx 26:0-55 57:7-25
[1]  @ ./redisinsight/ui/src/components/main/MainComponent.tsx 14:0-51 20:24-34
[1]  @ ./redisinsight/ui/src/App.tsx 25:0-60 117:38-51
[1]  @ ./redisinsight/ui/src/electron/AppElectron.tsx
[1]  @ ./redisinsight/ui/indexElectron.tsx
[1] 
[1] 222 ERRORS in child compilations
[1] webpack 5.14.0 compiled with 337 errors in 54563 ms
```

**Comment by zalenskiSofteq** [comment]
Hi Joey Guerra
Could you run `npm rebuild node-sass`? for fix problem and then again run `yarn package`

**Comment by joeyguerra** [comment]
Hey Zalenski. Thanks for the suggestion.

Yes, I've tried `npm rebuild node-sass`. That particular command appears to succeed. But then when I execute `yarn install` again, I get more errors.

Ultimately, there's many issues with trying to build from source on an M1.

node-sass is deprecated
sqlite3 from `npmjs` requires a version of node-gyp that implements a python 2 syntax
@elastic/datemath requires moment, which is not found

I'm trying to solve each roadblock as they come up. I'm currently trying to figure out why `moment` is not found.

**Comment by zalenskiSofteq** [comment]
I think you shouldn't have removed yarn.lock files. 
After remove yarn.lock files and run `yarn install` yarn automatically update all dependencies. It may make a new errors for build

**Comment by joeyguerra** [comment]
Initially, I didn't. And there were other errors. Essentially, I can't just git clone and yarn install because there's errors.

**Comment by zalenskiSofteq** [comment]
We have in the plan a user story about migrate from `node-sass` to `dart-sass` and increase node version. 
May be it will help

**Comment by joeyguerra** [comment]
Yes. I think that's great. Should I close this issue then?

**Comment by zalenskiSofteq** [comment]
After implementation I will post a message here. I will ask you try again. If there are no problems we will close this issue.

On our m1 devices this issue isn't reproduce.

**Comment by joeyguerra** [comment]
Thank you.

**Comment by ViktarStarastsenka** [comment]
Hi @joeyguerra , the node and node-sass versions have been increased, please re-open the ticket if it is still relevant.
