### ISSUE TITLE
[Bug]: docker run does not start

### ISSUE THREAD

**Issue by timbmg** [RedisInsight/RedisInsight#970]
When I try to bring up redisinsight, the docker run command never finishes/hangs. I just run:
```bash
docker run --network host redislabs/redisinsight:1.12.1
 ```

When I hit keyboard interupt after some time it shows:
```
^CException ignored in atexit callback: <bound method Client.join of <analytics.client.Client object at 0x7f24b2467a90>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/analytics/client.py", line 310, in join
    consumer.join()
  File "/usr/local/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
```

Tried both on Mac (OS: 12.1, Docker version 20.10.17) and Linux (OS: Debian 10, Docker version 20.10.9).

**Comment by GnaneshKunal** [comment]
Hey @timbmg 

Can you try without `--net host`?

Try this:
```sh
docker run -p 8001:8001 redislabs/redisinsight:1.12.1
```

**Comment by timbmg** [comment]
I see, I was confused by not seeing any logs. It works. Thank you!
